version: '3'

services:

  db-course:
    container_name: db-course
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-course
      POSTGRES_USER: ismael
      POSTGRES_PASSWORD: Test123
    ports:
      - "5434:5434"
    command: -p 5434

  db-student:
    container_name: db-student
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db-student
      POSTGRES_USER: ismael
      POSTGRES_PASSWORD: Test123
    ports:
      - "5435:5435"
    command: -p 5435

  db-keycloak:
    container_name: db-keycloak
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_keycloak
      POSTGRES_USER: ismael
      POSTGRES_PASSWORD: Test123
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5433.

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.2
    command: ["start-dev"]
    ports:
      - "8181:8181"
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: ismael
      DB_PASSWORD: Test123
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181