server:
  port: 8085

spring:
  application:
    name: microservice-media-uploader

  datasource:
    url: jdbc:postgresql://localhost:5434/course-app
    username: ismael
    password: Test123
    validation-query: true
    test-on-borrow: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      format-sql: true

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}