server:
  port: 8086

spring:
  application:
    name: microservice-courses

  datasource:
    url: jdbc:postgresql://localhost:5434/db-course
    username: ismael
    password: Test123
    test-on-borrow: false
    validation-query: SELECT 1 FROM dual
  flyway:
    baselineOnMigrate: true
    user: ismael
    password: Test123
    schemas: public
    createSchemas: true
    location: db/migrations, db/specific/h2
    enabled: true
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/spring-courses/protocol/openid-connect/certs

  messages:
    basename: i18n/messages

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}