server:
  port: 8086

spring:
  application:
    name: microservice-courses

  datasource:
    url: jdbc:postgresql://localhost:5434/db-course
    username: ismael
    password: Test123
    test-on-borrow: false
    validation-query: SELECT 1 FROM dual
  jpa:
    show-sql: true
    hibernate:
      format-sql: true
      ddl-auto: none

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}